name: poads_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  animated_splash_screen: 
  assets_audio_player: ^3.0.6
  audioplayers: ^4.0.1
  babstrap_settings_screen:
  bloc: ^8.1.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  firebase_auth: ^4.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_image_slideshow: 
  flutter_slidable: ^2.0.0
  google_nav_bar:
  firebase_core: ^2.15.1
  flutter_screenutil:
  hexcolor: ^3.0.1
  provider: ^6.0.5
  mvc_pattern: ^7.4.0
  flutter_modular: ^3.4.1+1
  dependencies:
dev_dependencies:
  flutter_launcher_icons: "^0.12.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/micLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sound/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
